<?php

namespace Ono\MapBundle\Repository;

/**
 * IndefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
