<?php

namespace Ono\MapBundle\Repository;

/**
 * LikeResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
