<?php

namespace Ono\MapBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
  public function getQuestionsWithThemes(array $themesId)
  {
    $qb = $this->createQueryBuilder('q');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb
      ->innerJoin('q.themes', 't')
    ;

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('t.id', $themesId));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine
    $qb->groupBy('q.id, q.libQuestion');
    $qb->having('COUNT(q.id) = :themes_count');
    $qb->setParameter('themes_count', count($themesId));
    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function getQuestionsWithIds(array $ids)
  {
    $qb = $this->createQueryBuilder('q');

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('q.id', $ids));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

}
