<?php

namespace Ono\MapBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
  public function getNbUsedCount($tagId){
    $qb = $this->createQueryBuilder('t');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb
      ->innerJoin('t.article', 'a')
      ->addSelect('COUNT(t.id) AS amount');

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where('t.id = :tagId')
    ->setParameter("tagId", $tagId);
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
