CREATE TABLE mytable(
   country VARCHAR(20) NOT NULL PRIMARY KEY
  ,capital VARCHAR(18) NOT NULL
  ,lat    INT  NOT NULL
  ,lon    INT  NOT NULL
);

INSERT INTO mytable(country,capital,lat,lon) VALUES ('AFGHANISTAN','KABOUL',35,69);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('AFRIQUE DU SUD','PRETORIA',-26,28);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ALBANIE','TIRANA',41,20);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ALGERIE','ALGER',37,3);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ALLEMAGNE','BONN',51,7);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ANDORRE','ANDORRE-LA-VIEILLE',43,2);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ANGOLA','LOANDA',-9,13);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ANTIGUA','SAINT-JOHN''S',17,-62);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ARABIE SAOUDITE','AR RIYAD',25,47);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ARGENTINE','BUENOS AIRES',-35,-50);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('AUSTRALIE','CANBERRA',-35,149);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('AUTRICHE','VIENNE',48,16);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('AZERBAIDJAN','BAKOU',41,50);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BAHAMAS','NASSAU',25,-77);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BAHREIN','MANAMA',26,51);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BANGLADESH','DACCA',24,90);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BARBADE','BRIDGETOWN',13,-60);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BELARUS','MINSK',53,28);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BELGIQUE','BRUXELLES',51,4);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BELIZE','BELIZE CITY',18,-88);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BENIN','PORTO NOVO',6,2);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BERMUDES','MANILTON',32,-65);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BHOUTAN','THIMPHU-PUNAKHA',27,90);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BIRMANIE','RANGOON',17,96);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BOLIVIE','LA PAZ-SUCRE',-17,-65);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BOSNIE','SARAJEVO',44,18);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BOTSWANA','GABORONE',-22,24);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BRESIL','BRASILIA',-16,-48);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BRUNEI','BANDAR SERI[1]',5,115);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BULGARIE','SOFIA',43,23);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BURKINA FASO','OUADAGOUDOU',12,-2);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('BURUNDI','BUJUMBURA',-3,29);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CAMBODGE','PNOM PENH',11,104);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CAMEROUN','YAOUNDE',4,12);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CANADA','OTTAWA',45,-75);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CAP-VERT','PRAIA',18,-25);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CENTRAFRIQUE','BANGUI',4,19);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CHILI','SANTIAGO',-33,-71);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CHINE','PEKIN',40,116);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CHYPRE','NICOSIE',35,33);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('COLOMBIE','BOGOTA',5,-72);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('COMORES','MORONI',-12,43);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CONGO','BRAZZAVILLE',-4,15);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CONGO (EX-ZAIRE)','KINSHASA',-4,15);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('COREE DU NORD','PYONGYANG',40,127);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('COREE DU SUD','SEOUL',37,127);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('COSTA RICA','SAN JOSE',10,-84);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('COTE D''IVOIRE','YAMOUSSOUKRO',6,-6);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CROATIE','ZAGREB',46,16);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('CUBA','LA HAVANE',21,-80);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('DANEMARK','COPENHAGUE',56,10);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('DJIBOUTI','DJIBOUTI',12,43);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('DOMINICAINE','SAINT-DOMINGUE',18,-70);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('DOMINIQUE','ROSEAU',15,-61);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('EGYPTE','LE CAIRE',30,32);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('EMIRATS ARABES UNIS','ABU DHABI',24,54);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('EQUATEUR','QUITO',0,-78);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ÉRYTHRÉE','ASMARA',15,39);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ESPAGNE','MADRID',40,-4);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ESTONIE','TALLINN',59,25);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ETATS-UNIS','WASHINGTON',39,-77);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ETHIOPIE','ADDIS ABEBA',9,39);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('FIDJI','SUVA',-18,178);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('FINLANDE','HELSINKI',60,25);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('FORMOSE','TAIPEH',25,122);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('FRANCE','PARIS',49,2);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GABON','LIBREVILLE',0,9);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GAMBIE','BANJUL',13,-15);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GÉORGIE','TBILISSI',42,45);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GHANA','ACCRA',6,0);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GRECE','ATHENES',38,24);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GRENADE','SAINT-GEORGE''S',12,-62);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GUATEMALA','GUATEMAMLA CITY',15,-91);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GUINEE','CONAKRY',10,-14);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GUINEE EQUATORIALE','MALABO',2,10);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GUINEE-BISSAU','BISSAU',12,-16);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('GUYANA','GEORGETOWN',7,-58);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('HAITI','PORT-AU-PRINCE',19,-73);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('HONDURAS','TEGUCIGALPA',14,-87);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('HONGRIE','BUDAPEST',48,19);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('INDE','DELHI',29,77);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('INDONESIE','DJAKARTA',-6,107);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('IRAK','BAGDAD',31,48);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('IRAN','TEHERAN',33,52);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('IRLANDE','DUBLIN',53,-6);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ISLANDE','REYKJAVIK',64,-23);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ISRAEL','JERUSALEM',32,35);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ITALIE','ROME',42,12);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('JAMAIQUE','KINGSTON',18,-77);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('JAPON','TOKYO',36,150);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('JORDANIE','AMMAN',32,36);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('KAZAKHSTAN','ALMA-ATA',42,78);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('KENYA','NAIROBI',-1,37);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('KIRGHIZISTAN','BICHKEK',42,75);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('KIRIBATI','TARAWA',2,-157);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('KOWEIT','KOWEIT',29,48);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LAOS','VIENTIANE',18,103);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LESOTHO','MASERU',-29,27);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LETTONIE','RIGA',57,24);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LIBAN','BEYROUTH',34,35);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LIBERIA','MONROVIA',7,-10);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LIBYE','TRIPOLI',32,13);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LIECHTENSTEIN','VADUZ',47,10);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LITUANIE','VILNIUS',54,26);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('LUXEMBOURG','LUXEMBOURG',50,6);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MACÉDOINE','SKOPJE',42,21);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MADAGASCAR','ANTANANARIVO',-19,48);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MALAISIE','KUALA LUMPUR',3,102);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MALAWI','ZOMBA',-13,34);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MALDIVES','MALE',2,73);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MALI','BAMAKO',13,8);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MALTE','LA VALETTE',36,14);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MAROC','RABAT',33,-7);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MARSHALL','MAJURO',7,171);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MARTINIQUE','FORT-DE-FRANCE',15,-61);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MAURICE','PORT-LOUIS',19,57);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MAURITANIE','NOUAKCHOTT',20,10);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MEXIQUE','MEXICO',19,-99);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MICRONÉSIE','KOLONIA',7,158);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MONACO','MONACO',44,7);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MONGOLIE','OULAN BATOR',47,105);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('MOZAMBIQUE','MAPUTO',-26,33);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NAMIBIE','WINDHOEK',-22,17);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NAURU','MAKWA',-1,167);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NEPAL','KHATMANDOU',22,85);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NICARAGUA','MANAGUA',13,-85);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NIGER','NIAMEY',13,2);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NIGERIA','ABUJA',9,7);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NORVEGE','OSLO',60,11);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('NOUVELLE-ZELANDE','WELLINGTON',-41,175);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('OMAN','MASCATE',13,45);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('OUGANDA','KAMPALA',0,32);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('OUZBÉKISTAN','TACHKENT',41,69);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PAKISTAN','ISLAMABAD',34,73);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PANAMA','PANAMA',8,-80);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PAPOUASIE','PORT MORESBY',-5,145);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PARAGUAY','ASUNCION',-25,-58);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PAYS-BAS','LA HAYE',57,4);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PEROU','LIMA',-12,-77);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PHILIPPINES','MANILLE',15,121);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('POLOGNE','VARSOVIE',52,21);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PORTO RICO','SAN JUAN',18,-66);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('PORTUGAL','LISBONNE',39,-9);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('QATAR','DOHA',25,51);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ROUMANIE','BUCAREST',44,26);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ROYAUME-UNI','LONDRES',52,0);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('RUSSIE','MOSCOU',56,38);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('RWANDA','KIGALI',-2,30);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SAINTE-LUCIE','CASTRIES',14,-61);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SAINT-MARIN','SAINT-MARIN',44,12);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SAINT-VINCENT','KINGSTOWN',12,-61);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SALOMON','HONIARA',-10,155);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SALVADOR','SAN SALVADOR',14,-89);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SAMOA OCCIDENTALES','APIA',-12,-172);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SAO TOME-ET-PRINCIPE','SAO TOME',0,7);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SENEGAL','DAKAR',15,-18);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SERBIE','BELGRADE',45,20);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SEYCHELLES','PORT VICTORIA',-5,55);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SIERRA LEONE','FREETOWN',8,-13);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SINGAPOUR','SINGAPOUR',1,104);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SLOVAQUIE','BRATISLAVA',48,17);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SLOVÉNIE','LJUBLJANA',46,15);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SOMALIE','MOGADISCIO',2,45);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SOUDAN','KHARTOUM',16,33);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SRI LANKA','COLOMBO',7,80);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ST-KITTS-ET-NEVIS','BASSETERRE',17,-63);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SUEDE','STOCKHOLM',59,18);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SUISSE','BERNE',47,9);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SURINAME','PARAMARIBO',6,-55);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SWAZILAND','MBABANE',-26,32);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('SYRIE','DAMAS',33,36);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TADJIKISTAN','DOUCHAMBE',39,69);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TANZANIE','DAR-ES-SALAM',-7,39);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TCHAD','N''DJAMENA',12,15);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TCHÉQUIE','PRAGUE',50,14);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('THAILANDE','BANGKOK',14,101);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TIMOR ORIENTAL','DILI',-8,125);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TOGO','LOME',6,1);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TONGA','NUKU ALOFA',-20,-175);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TRINITE-ET-TOBAGO','PORT OF SPAIN',11,-61);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TUNISIE','TUNIS',37,10);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TURKMÉNIE','ACHKHABAD',38,59);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TURQUIE','ANKARA',40,33);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('TUVALU','FUNAFUTI',-8,180);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('URUGUAY','MONTEVIDEO',-35,-56);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('VANUATU','VILA',-17,167);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('VATICAN','CITE DU VATICAN',42,12);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('VENEZUELA','CARACAS',11,-67);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('VIETNAM','HANOI',26,106);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('YEMEN','SANAA',15,-44);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ZAMBIE','LUSAKA',-15,29);
INSERT INTO mytable(country,capital,lat,lon) VALUES ('ZIMBABWE','HARARE',-18,31);
