#promouvoir utilisateur
ono_promote_user:
    path:     /user/promote/{id}
    defaults: { _controller: OnoUserBundle:User:promote }
    requirements:
        id: \d+


#promouvoir utilisateur
ono_view_user:
    path:     /profile
    defaults: { _controller: OnoUserBundle:User:show }
