
#promouvoir utilisateur
ono_promote_user:
    path:     /user/promote/{id}
    defaults: { _controller: OnoUserBundle:User:promote }
    requirements:
        id: \d+


#voir utilisateur
ono_view_user:
    path:     /profile
    defaults: { _controller: OnoUserBundle:User:show }


#edit utilisateur
ono_edit_user:
    path:     /profile/edit
    defaults: { _controller: OnoUserBundle:User:edit }
