imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    bundles:
        - OnoMapBundle
        - OnoUserBundle
        - OnoUXInteractiveBundle
        - IvoryCKEditorBundle


doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

knp_gaufrette:
    stream_wrapper: ~

    adapters:
        resource_adapter:
            aws_s3:
                service_id: 'aws.s3'
                bucket_name: %env(S3_BUCKET)%
                options:
                    directory: 'resource_files'
    filesystems:
        resource_file_fs:
            adapter:    resource_adapter

aws:
    version: latest
    region: eu-west-1
    credentials:
        key:     %env(AWS_KEY)%
        secret:  %env(AWS_SECRET)%
    S3:
        version: '2006-03-01'

vich_uploader:
    storage:       gaufrette
    mappings:
        resource_file:
            uri_prefix:         "https://%env(S3_BUCKET)%.s3.amazonaws.com/resource_files"
            upload_destination: resource_file_fs
