# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
# app/config/security.yml

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Ono\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_EDITOR:      ROLE_USER
        ROLE_ADMIN:       [ROLE_EDITOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    editor:  { password: editorpass, roles: [ 'ROLE_EDITOR' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        main:
            id: fos_user.user_provider.username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            pattern: ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:     %secret%


    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/logout, roles: ROLE_USER }
      - { path: ^/admin.+ , roles: ROLE_ADMIN }
      - { path: ^/admin, roles: ROLE_ADMIN }


            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
