# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: Ono\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

        # arguments: [%fos_user.model.user.class%]

    app.form.profile:
        class: Ono\UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: fos_user_profile }

    # my_user_provider:
    #     class: "%my_user_provider.class%"
    #     arguments: ['@fos_user.user_manager', { facebook: facebook_id}]

    a_service:
        class: Aws\Credentials\Credentials
        arguments:
            - %aws_key%
            - %aws_secret%
