ono_map_homepage:
    path:     /
    defaults:
        _controller: OnoMapBundle:Map:index

ono_map_update_homepage:
    path:     /update/map
    defaults:
        _controller: OnoMapBundle:Map:update

ono_map_changelanguage:
    path:     /changeLanguage/{cdLang}
    defaults:
        _controller: OnoMapBundle:Map:changeLanguage
    requirements:
        cdLang: \w{2,6}


############
#  RESPONSE
############

ono_map_response_add:
    path:     /response/add/{id}
    defaults:
        _controller: OnoMapBundle:Response:add
    requirements:
        id: \d+


ono_map_response_view:
    path:     /response/view/{id}
    defaults:
        _controller: OnoMapBundle:Response:view
    requirements:
        id: \d+


ono_map_response_edit:
    path:     /response/edit/{id}
    defaults:
        _controller: OnoMapBundle:Response:edit
    requirements:
        id: \d+


ono_map_response_delete:
    path:     /response/delete/{id}
    defaults:
        _controller: OnoMapBundle:Response:delete
    requirements:
        id: \d+

ono_map_response_like:
    path:     /response/like/{id}
    defaults:
        _controller: OnoMapBundle:Response:like
    requirements:
        id: \d+

ono_map_response_unlike:
    path:     /response/unlike/{id}
    defaults:
        _controller: OnoMapBundle:Response:unlike
    requirements:
        id: \d+


############
#  Article
############

ono_map_article_index:
    path:     /articles
    defaults:
        _controller: OnoMapBundle:Article:index


ono_map_article_view:
    path:     /article/show/{id}
    defaults:
        _controller: OnoMapBundle:Article:show
    requirements:
        id: \d+

ono_map_article_view_from_tag:
    path:     /article/show/{id}/{tag}
    defaults:
        _controller: OnoMapBundle:Article:show
    requirements:
        id: \d+
        tag: \d+

ono_map_article_add:
    path:     /article/add
    defaults:
        _controller: OnoMapBundle:Article:add

ono_map_article_edit:
    path:     /article/edit/{id}
    defaults:
        _controller: OnoMapBundle:Article:edit
    requirements:
        id: \d+

ono_map_article_like:
    path:     /article/like/{id}
    defaults:
        _controller: OnoMapBundle:Article:like
    requirements:
        id: \d+

ono_map_article_unlike:
    path:     /article/unlike/{id}
    defaults:
        _controller: OnoMapBundle:Article:unlike
    requirements:
        id: \d+

ono_map_article_popup:
    path:     /article/{id}/popup/{tag}
    defaults:
        _controller: OnoMapBundle:Article:popup
    requirements:
        id: \d+
        tag: \d+

############
#  QUESTION
############

ono_map_question_view:
    path:     /question/view/{id}
    defaults:
        _controller: OnoMapBundle:Question:view
    requirements:
        id: \d+

ono_map_question_index:
    path:     /questions/{activeThemes}
    defaults:
        _controller: OnoMapBundle:Question:index
        activeThemes: false
    requirements:
        id: \d+

#########
#  THEMES
#########

ono_map_update_session_themes:
    path:     /update
    defaults:
        _controller: OnoMapBundle:Theme:updateSession

################
#  INDEFINITIONS
################

ono_map_indefinition_add:
    path:     /article/{article_id}/tags/{tag_id}/indefinitions/add
    defaults:
        _controller: OnoMapBundle:Indefinition:add
    requirements:
        article_id: \d+
        tag_id: \d+

################
#  TAGS
################

ono_map_tag_view:
    path:     /tag/view/{id}
    defaults:
        _controller: OnoMapBundle:Tag:view
    requirements:
        id: \d+


###############################################################
#                            ADMIN
###############################################################

ono_admin_home:
    path:   /admin
    defaults:
        _controller: OnoMapBundle:Admin:index


#################
#  ADMIN THEME
#################

#ajout thème
ono_admin_add_theme:
    path:   /admin/theme/add
    defaults:
        _controller: OnoMapBundle:Theme:add

#list thème
ono_admin_list_theme:
    path:   /admin/theme/list
    defaults:
        _controller: OnoMapBundle:Theme:list

#edit thème
ono_admin_edit_theme:
    path:   /admin/theme/edit/{id}
    defaults:
        _controller: OnoMapBundle:Theme:edit
    requirements:
        id: \d+


#delete thème
ono_admin_delete_theme:
    path:   /admin/theme/delete/{id}
    defaults:
        _controller: OnoMapBundle:Theme:delete
    requirements:
        id: \d+

##################
#  ADMIN Question
##################

#ajout question
ono_admin_add_question:
    path:   /admin/question/add
    defaults:
        _controller: OnoMapBundle:Question:add

#list questions
ono_admin_list_question:
    path:   /admin/question/list
    defaults:
        _controller: OnoMapBundle:Question:index
        activeThemes: false

#edit question
ono_admin_edit_question:
    path:   /admin/question/edit/{id}
    defaults:
        _controller: OnoMapBundle:Question:edit
    requirements:
        id: \d+



#delete question
ono_admin_delete_question:
    path:   /admin/question/delete/{id}
    defaults:
        _controller: OnoMapBundle:Question:delete
    requirements:
        id: \d+


#####################
#  ADMIN RESPONSE
#####################

#ajouter réponse
ono_admin_add_response:
    path:   /admin/response/add
    defaults:
        _controller: OnoMapBundle:Admin:addResponse


#list réponse
ono_admin_list_response:
    path:   /admin/response/list
    defaults:
        _controller: OnoMapBundle:Admin:listResponse

#edit response
ono_admin_edit_response:
    path:   /admin/response/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editResponse
    requirements:
        id: \d+

#delete response
ono_admin_delete_response:
    path:   /admin/response/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteResponse
    requirements:
        id: \d+

#####################
#  ADMIN COUNTRY
#####################

#ajouter pays
ono_admin_add_country:
    path:   /admin/country/add
    defaults:
        _controller: OnoMapBundle:Country:add

#list des pays
ono_admin_list_country:
    path:   /admin/country/list
    defaults:
        _controller: OnoMapBundle:Country:index

#edit country
ono_admin_edit_country:
    path:   /admin/country/edit/{id}
    defaults:
        _controller: OnoMapBundle:Country:edit
    requirements:
        id: \d+

#delete country
ono_admin_delete_country:
    path:   /admin/country/delete/{id}
    defaults:
        _controller: OnoMapBundle:Country:delete
    requirements:
        id: \d+

#####################
#  ADMIN LANGUAGE
#####################

#ajouter langue
ono_admin_add_language:
    path:   /admin/language/add
    defaults:
        _controller: OnoMapBundle:Language:add

#list des langues
ono_admin_list_language:
    path:   /admin/language/list
    defaults:
        _controller: OnoMapBundle:Language:index

#edit langue
ono_admin_edit_language:
    path:   /admin/language/edit/{id}
    defaults:
        _controller: OnoMapBundle:Language:edit
    requirements:
        id: \d+

#delete langue
ono_admin_delete_language:
    path:   /admin/language/delete/{id}
    defaults:
        _controller: OnoMapBundle:Language:delete
    requirements:
        id: \d+


#####################
#  ADMIN USERS
#####################

ono_admin_promote_user:
    path:   /admin/user/promote/{id}
    defaults:
        _controller: OnoUserBundle:User:promote
    requirements:
        id: \d+

#ajouter utilisateurs
ono_admin_add_user:
    path:   /admin/user/add
    defaults:
        _controller: OnoUserBundle:User:add


#list utilisateurs
ono_admin_list_user:
    path:   /admin/user/list
    defaults:
        _controller: OnoUserBundle:User:list

#edit user
ono_admin_edit_user:
    path:   /admin/user/edit/{id}
    defaults:
        _controller: OnoUserBundle:User:edit
    requirements:
        id: \d+

#delete user
ono_admin_delete_user:
    path:   /admin/user/delete/{id}
    defaults:
        _controller: OnoUserBundle:User:delete
    requirements:
        id: \d+



#####################
#  ADMIN Article
#####################

#ajouter langue
ono_admin_add_article:
    path:   /admin/article/add
    defaults:
        _controller: OnoMapBundle:Article:add

#list des langues
ono_admin_list_articles:
    path:   /admin/article/list
    defaults:
        _controller: OnoMapBundle:Article:index

#edit langue
ono_admin_edit_article:
    path:   /admin/article/edit/{id}
    defaults:
        _controller: OnoMapBundle:Article:edit
    requirements:
        id: \d+

#delete langue
ono_admin_delete_article:
    path:   /admin/article/delete/{id}
    defaults:
        _controller: OnoMapBundle:Article:delete
    requirements:
        id: \d+


#####################
#  ADMIN Tags
#####################

#ajouter langue
ono_admin_add_tag:
    path:   /admin/tag/add
    defaults:
        _controller: OnoMapBundle:Tag:add

#list des langues
ono_admin_list_tags:
    path:   /admin/tag/list
    defaults:
        _controller: OnoMapBundle:Tag:index

#edit langue
ono_admin_edit_tag:
    path:   /admin/tag/edit/{id}
    defaults:
        _controller: OnoMapBundle:Tag:edit
    requirements:
        id: \d+

#delete langue
ono_admin_delete_tag:
    path:   /admin/tag/delete/{id}
    defaults:
        _controller: OnoMapBundle:Tag:delete
    requirements:
        id: \d+

#####################
#  ADMIN Indefs
#####################

#ajouter indef
ono_admin_add_indefinition:
    path:   /admin/indefinition/add
    defaults:
        _controller: OnoMapBundle:Admin:addIndefinition

#list des indef
ono_admin_list_indefinitions:
    path:   /admin/indefinition/list
    defaults:
        _controller: OnoMapBundle:Admin:listIndefinition

#edit indef
ono_admin_edit_indefinition:
    path:   /admin/indefinition/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editIndefinition
    requirements:
        id: \d+

#delete indef
ono_admin_delete_indefinition:
    path:   /admin/indefinition/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteIndefinition
    requirements:
        id: \d+
