ono_map_homepage:
    path:     /
    defaults:
        _controller: OnoMapBundle:Map:index


############
#  RESPONSE
############
ono_map_response_add:
    path:     /response/add/{id}
    defaults:
        _controller: OnoMapBundle:Map:addResponse
    requirements:
        id: \d+


ono_map_response_view:
    path:     /response/view/{id}
    defaults:
        _controller: OnoMapBundle:Map:viewResponse
    requirements:
        id: \d+


ono_map_response_edit:
    path:     /response/edit/{id}
    defaults:
        _controller: OnoMapBundle:Map:editResponse
    requirements:
        id: \d+


ono_map_response_delete:
    path:     /response/delete/{id}
    defaults:
        _controller: OnoMapBundle:Map:deleteResponse
    requirements:
        id: \d+


############
#  QUESTION
############

ono_map_question_view:
    path:     /question/view/{id}
    defaults:
        _controller: OnoMapBundle:Map:viewQuestion
    requirements:
        id: \d+


###############################################################
#                            ADMIN
###############################################################

ono_admin_home:
    path:   /admin
    defaults:
        _controller: OnoMapBundle:Admin:index


#################
#  ADMIN THEME
#################

#ajout thème
ono_admin_add_theme:
    path:   /admin/theme/add
    defaults:
        _controller: OnoMapBundle:Admin:addTheme

#list thème
ono_admin_list_theme:
    path:   /admin/theme/list
    defaults:
        _controller: OnoMapBundle:Admin:listTheme

#edit thème
ono_admin_edit_theme:
    path:   /admin/theme/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editTheme
    requirements:
        id: \d+


#delete thème
ono_admin_delete_theme:
    path:   /admin/theme/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteTheme
    requirements:
        id: \d+

##################
#  ADMIN Question
##################

#ajout question
ono_admin_add_question:
    path:   /admin/question/add
    defaults:
        _controller: OnoMapBundle:Admin:addQuestion

#list questions
ono_admin_list_question:
    path:   /admin/question/list
    defaults:
        _controller: OnoMapBundle:Admin:listQuestion

#edit question
ono_admin_edit_question:
    path:   /admin/question/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editQuestion
    requirements:
        id: \d+


#delete question
ono_admin_delete_question:
    path:   /admin/question/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteQuestion
    requirements:
        id: \d+

#####################
#  ADMIN UTILISATEURS
#####################

#ajouter utilisateurs
ono_admin_add_user:
    path:   /admin/user/add
    defaults:
        _controller: OnoMapBundle:Admin:addUser


#list utilisateurs
ono_admin_list_user:
    path:   /admin/user/list
    defaults:
        _controller: OnoMapBundle:Admin:listUser

#edit user
ono_admin_edit_user:
    path:   /admin/user/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editUser
    requirements:
        id: \d+

#delete user
ono_admin_delete_user:
    path:   /admin/user/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteUser
    requirements:
        id: \d+

#####################
#  ADMIN RESPONSE
#####################

#ajouter réponse
ono_admin_add_response:
    path:   /admin/response/add
    defaults:
        _controller: OnoMapBundle:Admin:addResponse


#list réponse
ono_admin_list_response:
    path:   /admin/response/list
    defaults:
        _controller: OnoMapBundle:Admin:listResponse

#edit response
ono_admin_edit_response:
    path:   /admin/response/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editResponse
    requirements:
        id: \d+

#delete response
ono_admin_delete_response:
    path:   /admin/response/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteResponse
    requirements:
        id: \d+

#####################
#  ADMIN COUNTRY
#####################

#ajouter pays
ono_admin_add_country:
    path:   /admin/country/add
    defaults:
        _controller: OnoMapBundle:Admin:addCountry

#list des pays
ono_admin_list_country:
    path:   /admin/country/list
    defaults:
        _controller: OnoMapBundle:Admin:listCountry

#edit country
ono_admin_edit_country:
    path:   /admin/country/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editCountry
    requirements:
        id: \d+

#delete country
ono_admin_delete_country:
    path:   /admin/country/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteCountry
    requirements:
        id: \d+

#####################
#  ADMIN LANGUAGE
#####################

#ajouter langue
ono_admin_add_language:
    path:   /admin/language/add
    defaults:
        _controller: OnoMapBundle:Admin:addLanguage

#list des langues
ono_admin_list_language:
    path:   /admin/language/list
    defaults:
        _controller: OnoMapBundle:Admin:listLanguage

#edit langue
ono_admin_edit_language:
    path:   /admin/language/edit/{id}
    defaults:
        _controller: OnoMapBundle:Admin:editLanguage
    requirements:
        id: \d+

#delete langue
ono_admin_delete_language:
    path:   /admin/language/delete/{id}
    defaults:
        _controller: OnoMapBundle:Admin:deleteLanguage
    requirements:
        id: \d+
