services:
    app.twig_extension:
        class: Ono\MapBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            container: "@service_container"
            token: "@security.token_storage"
